apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- file.yml
# Kustomize [eschews](https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/#removal-directives)
# including resources for a yml you don't want built, but we need to build the yml
# for the replacement to work.
- overlay.yml

replacements:
- source:
    kind: Configmap
    name: runbooks
    fieldPath: data.[name=two].runbook
  targets:
  - select:
      kind: Namespace
      name: file
    fieldpaths:
    - metadata.stuff.[name=two].runbook
